package it.polimi.demo.view.flow.utilities.events;

public enum EventType {
    APP_MENU,
    PLAYER_JOINED,
    JOIN_UNABLE_GAME_FULL,
    JOIN_UNABLE_NICKNAME_ALREADY_IN,
    GAME_ID_NOT_EXISTS,
    GENERIC_ERROR_WHEN_ENTERING_GAME,
    PLAYER_IS_READY_TO_START,
    GAME_STARTED,
    GAME_ENDED,
    MESSAGE_SENT,
    ASK_WHICH_ORIENTATION,
    ILLEGAL_MOVE,
    CARD_PLACED,
    NEXT_TURN,
    PLAYER_DISCONNECTED,
    PLAYER_RECONNECTED
}
