package it.polimi.demo.view.flow.utilities.events;

public enum EventType {
    APP_MENU,
    PLAYER_JOINED,
    JOIN_UNABLE_GAME_FULL,
    JOIN_UNABLE_NICKNAME_ALREADY_IN,
    GAME_ID_NOT_EXISTS,
    GENERIC_ERROR_WHEN_ENTRYING_GAME,
    PLAYER_IS_READY_TO_START,
    GAMESTARTED,
    GAMEENDED,
    SENT_MESSAGE,
    CARD_PLACED,
    ASK_COORDINATES_TO_PLACE_CARD,
    NEXT_TURN,
    PLAYER_DISCONNECTED,
    PLAYER_RECONNECTED
}
